// <auto-generated />
using API_CRUD_ejercicioUno.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API_CRUD_ejercicioUno.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20231016123601_AgregarProducto")]
    partial class AgregarProducto
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API_CRUD_ejercicioUno.Models.Producto", b =>
                {
                    b.Property<int>("IdProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProducto"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdProducto");

                    b.ToTable("producto");

                    b.HasData(
                        new
                        {
                            IdProducto = 1,
                            Cantidad = 20,
                            Descripcion = "High Fantasy",
                            Nombre = "A Court of Thorns and Roses"
                        },
                        new
                        {
                            IdProducto = 2,
                            Cantidad = 20,
                            Descripcion = "High Fantasy",
                            Nombre = "A Court of Mist and Fury"
                        },
                        new
                        {
                            IdProducto = 3,
                            Cantidad = 20,
                            Descripcion = "High Fantasy",
                            Nombre = "A Court of Wind and Ruins"
                        },
                        new
                        {
                            IdProducto = 4,
                            Cantidad = 20,
                            Descripcion = "High Fantasy",
                            Nombre = "A Court of Frost and Starlight"
                        },
                        new
                        {
                            IdProducto = 5,
                            Cantidad = 20,
                            Descripcion = "High Fantasy",
                            Nombre = "A Court of Silver Flames"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
